# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value
    twig.config:
      debug: true

services:
    my_rules_manager:
       class: app\IndexBundle\Controller\SistemaReglas\SistemaReglas
       arguments: ["@doctrine.orm.default_entity_manager", "@doctrine.orm.vamp_entity_manager"]
    my_password_encoder:
       class: app\IndexBundle\Controller\PartidaEncoder
    my_form_editor:
       class: app\IndexBundle\Controller\Listener\AddGamesFieldSubscriber
       arguments: ["@doctrine.orm.default_entity_manager", "@doctrine.orm.vamp_entity_manager", "@my_password_encoder"]
