app_select_screen:
    path:     /
    defaults: { _controller: appIndexBundle:Index:select }

app_index_homepage:
    path:     /reglas
    defaults: { _controller: appIndexBundle:Index:index }

app_rolManageDD35_screen:
    path:     /DD35Master
    defaults: { _controller: appIndexBundle:DD35:DD35 }

app_rolManageVampiro_screen:
    path:     /VampiroMaster
    defaults: { _controller: appIndexBundle:Vampiro:Vampiro }

app_DD35Create_screen:
    path:     /DD35Master/crear
    defaults: { _controller: appIndexBundle:DD35:DD35Create }

app_DD35CreateP_screen:
    path:     /DD35Master/crearPlantilla
    defaults: { _controller: appIndexBundle:DD35:DD35CreateP }

app_DD35Change_screen:
    path:     /DD35Master/modificar
    defaults: { _controller: appIndexBundle:DD35:DD35Change }

app_DD35Delete_screen:
    path:     /DD35Master/eliminar
    defaults: { _controller: appIndexBundle:DD35:DD35Delete }

app_DD35DeleteP_screen:
    path:     /DD35Master/eliminarPlantilla
    defaults: { _controller: appIndexBundle:DD35:DD35DeleteP }

app_DD35CreateW_screen:
    path:     /DD35Master/crearArma
    defaults: { _controller: appIndexBundle:DD35:DD35CreateW }

app_DD35DeleteW_screen:
    path:     /DD35Master/eliminarArma
    defaults: { _controller: appIndexBundle:DD35:DD35DeleteW }

app_VampiroCreate_screen:
    path:     /VampiroMaster/crear
    defaults: { _controller: appIndexBundle:Vampiro:VampiroCreate }

app_VampiroCreateP_screen:
    path:     /VampiroMaster/crearPlantilla
    defaults: { _controller: appIndexBundle:Vampiro:VampiroCreateP }

app_VampiroChange_screen:
    path:     /VampiroMaster/modificar
    defaults: { _controller: appIndexBundle:Vampiro:VampiroChange }

app_VampiroDelete_screen:
    path:     /VampiroMaster/eliminar
    defaults: { _controller: appIndexBundle:Vampiro:VampiroDelete }

app_VampiroDeleteP_screen:
    path:     /VampiroMaster/eliminarPlantilla
    defaults: { _controller: appIndexBundle:Vampiro:VampiroDeleteP }

app_VampiroCreateW_screen:
    path:     /VampiroMaster/crearArma
    defaults: { _controller: appIndexBundle:Vampiro:VampiroCreateW }

app_VampiroDeleteW_screen:
    path:     /VampiroMaster/eliminarArma
    defaults: { _controller: appIndexBundle:Vampiro:VampiroDeleteW }

login:
    path:     /login
    defaults: { _controller: appIndexBundle:Security:login }

logout:
    path:     /logout
    defaults: { _controller: appIndexBundle:Security:logout }

register:
    path:     /registro
    defaults: { _controller: appIndexBundle:Security:register }